import Foundation

// Ukrainian translations for Billing & Paywall UI.
let ukBillingStrings: [String: String] = [
    // PaywallView
    "Packs are unavailable right now. Please try again in a moment.": "Набори тимчасово недоступні. Спробуй ще раз за мить.",
    "Full pricing details": "Докладно про ціни",
    "Treats never expire. One-time purchase — no subscription.": "Смаколики не згорають. Одна покупка — жодних підписок.",
    "Get Treats": "Поповнити смаколики",
    "Close": "Закрити",
    "%@ treats": "%@ смаколиків",
    "Pick a pack to keep your lessons going.": "Обери набір, щоб уроки не зупинялися.",
    "What treats cost": "На що йдуть смаколики",
    "Chat reply": "Відповідь у чаті",
    "~5 treats": "~5 смаколиків",
    "Voice line": "Озвучена репліка",
    "~2 treats": "~2 смаколики",
    "Street View photo chat": "Чат про фото зі Street View",
    "Street View photo labels": "Підписи до фото зі Street View",
    "Add to Memorise": "Додати до Пам'яті",
    "Verb check": "Перевірка дієслова",
    "~3 treats": "~3 смаколики",
    "~9 treats": "~9 смаколиків",
    "Have a coupon code?": "Є промокод?",
    "Enter code": "Введи код",
    "Apply": "Застосувати",
    "%@ treats added to your balance!": "%@ смаколиків додано на баланс!",
    "This coupon code is not valid.": "Цей промокод недійсний.",
    "This coupon has expired.": "У цього промокоду вийшов термін дії.",
    "This coupon has reached its usage limit.": "Цей промокод вичерпав ліміт використань.",
    "You've already redeemed this coupon.": "Цей промокод уже активовано.",
    "Something went wrong. Please try again.": "Щось пішло не так. Спробуй ще раз.",

    // BillingInfoView
    "A full AI answer from your tutor.": "Повна відповідь від твого AI-репетитора.",
    "Hearing a reply spoken aloud.": "Озвучення відповіді вголос.",
    "Asking the tutor about a photo you've taken.": "Питання репетитору про твоє фото.",
    "Identifying and labelling objects in your photo.": "Розпізнавання й підписування об'єктів на фото.",
    "Generates the repeat-audio and picture for a new word or phrase.": "Створює аудіо для повторення та картинку для нового слова чи фрази.",
    "Checking your spoken answer in Verbs & Times.": "Перевірка твоєї усної відповіді в «Дієсловах і часах».",
    "~6 treats": "~6 смаколиків",
    "How treats work": "Як працюють смаколики",
    "Done": "Готово",
    "Treats power your Spanish": "Смаколики рухають твою іспанську",
    "Treats are the credit that runs the AI features — chat, voice, Street View and drills. You buy them once and spend them as you learn.": "Смаколики — це паливо для AI-функцій: чату, голосу, Street View і тренувань. Купуєш їх один раз і витрачаєш під час навчання.",
    "What are treats?": "Що таке смаколики?",
    "Every reply, spoken line and photo is generated live by AI, which has a real cost on our side. Treats are how that cost is shared fairly: simple actions use a little, richer ones use a bit more. New accounts start with free treats so you can try everything before paying.": "Кожну відповідь, репліку й фото AI створює наживо, а це коштує нам реальних грошей. Смаколики — це чесний спосіб розділити цю вартість: прості дії коштують трохи, складніші — трохи більше. Новачки отримують безкоштовні смаколики, щоб усе спробувати ще до оплати.",
    "What uses treats": "На що витрачаються смаколики",
    "Amounts are approximate and may be adjusted over time.": "Суми приблизні й можуть змінюватися з часом.",
    "Ways to spend less": "Як витрачати менше",
    "Turn off automatic voice replies in Profile and tap a message only when you want to hear it — voice is the easiest way to save.": "Вимкни автоозвучення у Профілі й торкайся повідомлення лише тоді, коли хочеш його почути — на голосі заощадити найлегше.",
    "Chatting in text uses the fewest treats.": "Текстове спілкування витрачає найменше смаколиків.",
    "How top-ups work": "Як працює поповнення",
    "Pick any pack to add treats instantly. Bigger packs include bonus treats, so you get more for each dollar:": "Обери будь-який набір — і смаколики додаються миттєво. У більших наборах є бонусні смаколики, тож за кожен долар ти отримуєш більше:",
    "How we calculate": "Як ми рахуємо",
    "Treat costs reflect the real work behind each action: a longer answer or a spoken line costs a little more than a short text reply. We round everything to simple, predictable amounts so you always have a rough idea of what you're spending — no surprises, no per-word meter.": "Ціна у смаколиках відображає справжню роботу за кожною дією: довша відповідь чи озвучена репліка коштує трохи більше, ніж короткий текст. Ми округлюємо все до простих, зрозумілих чисел, тож ти завжди приблизно знаєш свої витрати — жодних сюрпризів і жодного лічильника за кожне слово.",
    "Good to know": "Корисно знати",
    "Treats never expire.": "Смаколики не згорають.",
    "Treat packs are one-time purchases, not a subscription — you're never charged automatically.": "Набори смаколиків — це одноразові покупки, а не підписка: кошти ніколи не списуються автоматично.",
    "When you run low, top up any pack to keep going.": "Коли смаколиків меншає, поповни будь-яким набором — і навчайся далі.",
    "Terms & Conditions": "Умови та положення",
    "Privacy Policy": "Політика конфіденційності",
]
