-- Professor Madrid — Social Core: friendships, blocks, invite links
-- Migration: 20260718000000_social_core.sql
--
-- What this adds:
--   1. friendships   — one canonical edge per unordered user pair, with a status
--      lifecycle (pending → accepted / declined / removed).
--   2. blocks        — one-directional silent blocks. Blocking removes the
--      friendship and makes every future invite/share from the blocked user
--      silently no-op (the blocked party never learns about the block).
--   3. invite_links  — shareable tokens. mode 'one_time' (first claimant wins,
--      then dead) or 'reusable' (anyone joining via it befriends the inviter).
--      target_email is set when the link was created for a specific address.
--   4. RPCs          — find_user_by_email (auth.users lookup for the proxy),
--      claim_invite (atomic claim + friendship upsert; the ONLY place the
--      one-time race is resolved).
--
-- Access model: clients get RLS SELECT on their own view of the graph; ALL
-- mutations go through the Railway proxy (service_role) because they touch rows
-- the caller does not own. Emails are stored lowercased and compared lower().

-- ─── 1. friendships ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS friendships (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  -- user_a = requester (who sent the invite / owned the claimed link)
  user_a        UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- user_b = addressee (who accepts / declines)
  user_b        UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status        TEXT        NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending','accepted','declined','removed')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  responded_at  TIMESTAMPTZ,
  CHECK (user_a <> user_b)
);

-- One live edge per unordered pair, regardless of direction.
CREATE UNIQUE INDEX IF NOT EXISTS friendships_pair_uniq
  ON friendships (LEAST(user_a, user_b), GREATEST(user_a, user_b));

CREATE INDEX IF NOT EXISTS friendships_user_b_status_idx
  ON friendships (user_b, status);
CREATE INDEX IF NOT EXISTS friendships_user_a_status_idx
  ON friendships (user_a, status);

ALTER TABLE friendships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "friendships_participant_read" ON friendships
  FOR SELECT USING (auth.uid() = user_a OR auth.uid() = user_b);

CREATE POLICY "friendships_service" ON friendships
  FOR ALL TO service_role USING (true);

-- ─── 2. blocks ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS blocks (
  blocker_id  UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  blocked_id  UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);

ALTER TABLE blocks ENABLE ROW LEVEL SECURITY;

-- Only the blocker can see their own blocks (the block is invisible to the blocked).
CREATE POLICY "blocks_owner_read" ON blocks
  FOR SELECT USING (auth.uid() = blocker_id);

CREATE POLICY "blocks_service" ON blocks
  FOR ALL TO service_role USING (true);

-- ─── 3. invite_links ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS invite_links (
  -- 22-char base64url token from 16 random bytes; generated by the proxy.
  token         TEXT        PRIMARY KEY,
  inviter_id    UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  mode          TEXT        NOT NULL CHECK (mode IN ('one_time','reusable')),
  -- Lowercased. Set when the link was created for a specific email that had no
  -- account yet; the /v1/bootstrap claim step converts it into a pending
  -- friendship when that email signs up.
  target_email  TEXT,
  claimed_by    UUID        REFERENCES auth.users(id) ON DELETE SET NULL,
  claimed_at    TIMESTAMPTZ,
  revoked_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS invite_links_inviter_idx
  ON invite_links (inviter_id, created_at DESC);
CREATE INDEX IF NOT EXISTS invite_links_target_email_idx
  ON invite_links (lower(target_email)) WHERE target_email IS NOT NULL;

ALTER TABLE invite_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "invite_links_owner_read" ON invite_links
  FOR SELECT USING (auth.uid() = inviter_id);

CREATE POLICY "invite_links_service" ON invite_links
  FOR ALL TO service_role USING (true);

-- ─── 4. RPCs ─────────────────────────────────────────────────────────────────

-- auth.users is not exposed over PostgREST, so the proxy resolves emails via
-- this definer function. Returns NULL when no account exists.
CREATE OR REPLACE FUNCTION find_user_by_email(p_email TEXT)
RETURNS UUID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, auth
AS $$
  SELECT id FROM auth.users WHERE lower(email) = lower(p_email) LIMIT 1;
$$;

-- Inverse lookup: the proxy needs a friend's email to write song_shares rows
-- (recipient identity is email-keyed so it survives account deletion/recreation).
CREATE OR REPLACE FUNCTION find_email_by_user_id(p_user UUID)
RETURNS TEXT
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, auth
AS $$
  SELECT lower(email) FROM auth.users WHERE id = p_user LIMIT 1;
$$;

-- Lock the definer functions down to the service role only.
REVOKE EXECUTE ON FUNCTION find_user_by_email(TEXT) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION find_email_by_user_id(UUID) FROM PUBLIC, anon, authenticated;

-- Atomic invite claim. The conditional UPDATE on one_time links is the single
-- source of truth for the first-claimant-wins race: exactly one concurrent
-- caller sees the row flip. Reusable links skip the claim write.
--
-- Returns { result, inviter_id } where result ∈
--   created | already_friends | dead_link | self_invite | blocked
-- 'blocked' is returned to the PROXY only — it must present it to the claimant
-- as a generic failure so blocks stay silent.
CREATE OR REPLACE FUNCTION claim_invite(p_token TEXT, p_user UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  inv        invite_links;
  edge       friendships;
BEGIN
  SELECT * INTO inv FROM invite_links
   WHERE token = p_token AND revoked_at IS NULL
   FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('result', 'dead_link');
  END IF;

  IF inv.inviter_id = p_user THEN
    RETURN jsonb_build_object('result', 'self_invite', 'inviter_id', inv.inviter_id);
  END IF;

  -- Silent block check, both directions.
  IF EXISTS (
    SELECT 1 FROM blocks
     WHERE (blocker_id = inv.inviter_id AND blocked_id = p_user)
        OR (blocker_id = p_user AND blocked_id = inv.inviter_id)
  ) THEN
    RETURN jsonb_build_object('result', 'blocked', 'inviter_id', inv.inviter_id);
  END IF;

  IF inv.mode = 'one_time' THEN
    UPDATE invite_links
       SET claimed_by = p_user, claimed_at = now()
     WHERE token = p_token AND claimed_by IS NULL;
    IF NOT FOUND THEN
      -- Already claimed. If this same user claimed it earlier, it's idempotent.
      IF inv.claimed_by = p_user THEN
        RETURN jsonb_build_object('result', 'already_friends', 'inviter_id', inv.inviter_id);
      END IF;
      RETURN jsonb_build_object('result', 'dead_link');
    END IF;
  END IF;

  -- Upsert the friendship edge. Claiming a link is an active mutual gesture
  -- (inviter created it, claimant clicked it), so the edge goes straight to
  -- accepted — including reviving a previously removed/declined edge.
  SELECT * INTO edge FROM friendships
   WHERE LEAST(user_a, user_b) = LEAST(inv.inviter_id, p_user)
     AND GREATEST(user_a, user_b) = GREATEST(inv.inviter_id, p_user)
   FOR UPDATE;

  IF FOUND THEN
    IF edge.status = 'accepted' THEN
      RETURN jsonb_build_object('result', 'already_friends', 'inviter_id', inv.inviter_id);
    END IF;
    UPDATE friendships
       SET status = 'accepted', responded_at = now()
     WHERE id = edge.id;
  ELSE
    INSERT INTO friendships (user_a, user_b, status, responded_at)
    VALUES (inv.inviter_id, p_user, 'accepted', now());
  END IF;

  RETURN jsonb_build_object('result', 'created', 'inviter_id', inv.inviter_id);
END;
$$;

REVOKE EXECUTE ON FUNCTION claim_invite(TEXT, UUID) FROM PUBLIC, anon, authenticated;
